# -*- coding: utf-8 -*-
"""Translator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GlM-KZtD9d3FeKMTMEt3NNrzgpfvlMcq
"""

!pip install transformers
!pip install datasets
!pip install sentencepiece
!pip install evaluate
!pip install sacrebleu

# !head -5 news_talk_en_ko_train_130000.tsv

# 데이터셋 다운받기 위한 import
from datasets import load_dataset

# 데이터셋 받아오기
en_ko = load_dataset("bongsoo/news_talk_en_ko")

en_ko

import pandas as pd

# 판다스로 포맷으로 데이터셋 세팅
en_ko.set_format(type='pandas')

# train 모든 행 dafr에 삽입
df = en_ko["train"][:]

# 위의 5줄 출력 (첫 줄이 헤더로 잡힙 문제)
df.head()

example_0 = list(df.columns)
example_0

# dafr.split('')
# en = dafr[0].strip()
# ko = [1].strip()
# for i in df.readlines():
#   i = i.split(' ')
#   en = i[0].strip()
#   ko = i[1].strip()

example_0_df = pd.DataFrame({col: [value] for col, value in zip(('en', 'ko'), example_0)})

df.columns = ('en', 'ko')

en_ko_df = pd.concat([example_0_df, df],).reset_index(drop = True)
en_ko_df.head()

from datasets import Dataset

dataset = Dataset.from_pandas(en_ko_df)